const tarotCards = {
    "0": {
        "ID": "0",
        "Name": "The Fool",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "",
        "Planet": "Uranus",
        "Sign": "",
        "Element": "Air",
        "Septenary": "Zero",
        "Vertical": "Zero"
    },
    "1": {
        "ID": "1",
        "Name": "The Magician",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "One",
        "Planet": "Mercury",
        "Sign": "",
        "Element": "",
        "Septenary": "First",
        "Vertical": "First"
    },
    "2": {
        "ID": "2",
        "Name": "The High Priestess",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Two",
        "Planet": "Moon",
        "Sign": "",
        "Element": "",
        "Septenary": "First",
        "Vertical": "Second"
    },
    "3": {
        "ID": "3",
        "Name": "The Empress",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Three",
        "Planet": "Venus",
        "Sign": "",
        "Element": "",
        "Septenary": "First",
        "Vertical": "Third"
    },
    "4": {
        "ID": "4",
        "Name": "The Emperor",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Four",
        "Planet": "",
        "Sign": "Aries",
        "Element": "",
        "Septenary": "First",
        "Vertical": "Forth"
    },
    "5": {
        "ID": "5",
        "Name": "The Hierophant",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Five",
        "Planet": "",
        "Sign": "Taurus",
        "Element": "",
        "Septenary": "First",
        "Vertical": "Fifth"
    },
    "6": {
        "ID": "6",
        "Name": "The Lovers",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Six",
        "Planet": "",
        "Sign": "Gemini",
        "Element": "",
        "Septenary": "First",
        "Vertical": "Sixth "
    },
    "7": {
        "ID": "7",
        "Name": "The Chariot",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Seven",
        "Planet": "",
        "Sign": "Cancer",
        "Element": "",
        "Septenary": "First",
        "Vertical": "Seventh"
    },
    "8": {
        "ID": "8",
        "Name": "Strength",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Eight",
        "Planet": "",
        "Sign": "Leo",
        "Element": "",
        "Septenary": "Second",
        "Vertical": "First"
    },
    "9": {
        "ID": "9",
        "Name": "The Hermit",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Nine",
        "Planet": "",
        "Sign": "Virgo",
        "Element": "",
        "Septenary": "Second",
        "Vertical": "Second"
    },
    "10": {
        "ID": "10",
        "Name": "Wheel Of Fortune",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "One",
        "Planet": "Jupiter",
        "Sign": "",
        "Element": "",
        "Septenary": "Second",
        "Vertical": "Third"
    },
    "11": {
        "ID": "11",
        "Name": "Justice",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Two",
        "Planet": "",
        "Sign": "Libra",
        "Element": "",
        "Septenary": "Second",
        "Vertical": "Forth"
    },
    "12": {
        "ID": "12",
        "Name": "The Hanged Man",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Three",
        "Planet": "Neptune",
        "Sign": "",
        "Element": "Water",
        "Septenary": "Second",
        "Vertical": "Fifth"
    },
    "13": {
        "ID": "13",
        "Name": "Death",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Four",
        "Planet": "",
        "Sign": "Scorpio",
        "Element": "",
        "Septenary": "Second",
        "Vertical": "Sixth"
    },
    "14": {
        "ID": "14",
        "Name": "Temperance",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Five",
        "Planet": "",
        "Sign": "Sagittarius",
        "Element": "",
        "Septenary": "Second",
        "Vertical": "Seventh"
    },
    "15": {
        "ID": "15",
        "Name": "The Devil",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Six",
        "Planet": "",
        "Sign": "Capricorn",
        "Element": "",
        "Septenary": "Third",
        "Vertical": "First"
    },
    "16": {
        "ID": "16",
        "Name": "The Tower",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Seven",
        "Planet": "Mars",
        "Sign": "",
        "Element": "",
        "Septenary": "Third",
        "Vertical": "Second"
    },
    "17": {
        "ID": "17",
        "Name": "The Star",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Eight",
        "Planet": "",
        "Sign": "Aquarius",
        "Element": "",
        "Septenary": "Third",
        "Vertical": "Third"
    },
    "18": {
        "ID": "18",
        "Name": "The Moon",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Nine",
        "Planet": "",
        "Sign": "Pisces",
        "Element": "",
        "Septenary": "Third",
        "Vertical": "Forth"
    },
    "19": {
        "ID": "19",
        "Name": "The Sun",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "One",
        "Planet": "Sun",
        "Sign": "",
        "Element": "",
        "Septenary": "Third",
        "Vertical": "Fifith"
    },
    "20": {
        "ID": "20",
        "Name": "Judgment",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Two",
        "Planet": "Pluto",
        "Sign": "",
        "Element": "Fire",
        "Septenary": "Third",
        "Vertical": "Sixth"
    },
    "21": {
        "ID": "21",
        "Name": "The World",
        "Suit": "Majors",
        "Type": "Majors",
        "Numerology": "Three",
        "Planet": "Saturn",
        "Sign": "",
        "Element": "",
        "Septenary": "Third",
        "Vertical": "Seventh"
    },
    "101": {
        "ID": "101",
        "Name": "Ace of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "One",
        "Planet": "",
        "Sign": "",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "102": {
        "ID": "102",
        "Name": "2 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "Two",
        "Planet": "Mars",
        "Sign": "Aries",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "103": {
        "ID": "103",
        "Name": "3 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "Three",
        "Planet": "Sun",
        "Sign": "Aries",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "104": {
        "ID": "104",
        "Name": "4 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "Four",
        "Planet": "Mercury",
        "Sign": "Aries",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "105": {
        "ID": "105",
        "Name": "5 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "Five",
        "Planet": "Saturn",
        "Sign": "Leo",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "106": {
        "ID": "106",
        "Name": "6 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "Six",
        "Planet": "Jupiter",
        "Sign": "Leo",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "107": {
        "ID": "107",
        "Name": "7 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "Seven",
        "Planet": "Mars",
        "Sign": "Leo",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "108": {
        "ID": "108",
        "Name": "8 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "Eight",
        "Planet": "Mercury",
        "Sign": "Sagittarius",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "109": {
        "ID": "109",
        "Name": "9 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "Nine",
        "Planet": "Moon",
        "Sign": "Sagittarius",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "110": {
        "ID": "110",
        "Name": "10 of Wands",
        "Suit": "Wands",
        "Type": "Minors",
        "Numerology": "One",
        "Planet": "Saturn",
        "Sign": "Sagittarius",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "111": {
        "ID": "111",
        "Name": "Page of Wands",
        "Suit": "Wands",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "112": {
        "ID": "112",
        "Name": "Knight of Wands",
        "Suit": "Wands",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "113": {
        "ID": "113",
        "Name": "Queen of Wands",
        "Suit": "Wands",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "114": {
        "ID": "114",
        "Name": "King of Wands",
        "Suit": "Wands",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Fire",
        "Septenary": "",
        "Vertical": ""
    },
    "201": {
        "ID": "201",
        "Name": "Ace of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "One",
        "Planet": "",
        "Sign": "",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "202": {
        "ID": "202",
        "Name": "2 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "Two",
        "Planet": "Venus",
        "Sign": "Cancer",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "203": {
        "ID": "203",
        "Name": "3 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "Three",
        "Planet": "Mercury",
        "Sign": "Cancer",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "204": {
        "ID": "204",
        "Name": "4 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "Four",
        "Planet": "Moon",
        "Sign": "Cancer",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "205": {
        "ID": "205",
        "Name": "5 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "Five",
        "Planet": "Mars",
        "Sign": "Scorpio",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "206": {
        "ID": "206",
        "Name": "6 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "Six",
        "Planet": "Sun",
        "Sign": "Scorpio",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "207": {
        "ID": "207",
        "Name": "7 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "Seven",
        "Planet": "Venus",
        "Sign": "Scorpio",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "208": {
        "ID": "208",
        "Name": "8 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "Eight",
        "Planet": "Saturn",
        "Sign": "Pisces",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "209": {
        "ID": "209",
        "Name": "9 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "Nine",
        "Planet": "Jupiter",
        "Sign": "Pisces",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "210": {
        "ID": "210",
        "Name": "10 of Cups",
        "Suit": "Cups",
        "Type": "Minors",
        "Numerology": "One",
        "Planet": "Mars",
        "Sign": "Pisces",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "211": {
        "ID": "211",
        "Name": "Page of Cups",
        "Suit": "Cups",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "212": {
        "ID": "212",
        "Name": "Knight of Cups",
        "Suit": "Cups",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "213": {
        "ID": "213",
        "Name": "Queen of Cups",
        "Suit": "Cups",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "214": {
        "ID": "214",
        "Name": "King of Cups",
        "Suit": "Cups",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Water",
        "Septenary": "",
        "Vertical": ""
    },
    "401": {
        "ID": "401",
        "Name": "Ace of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "One",
        "Planet": "",
        "Sign": "",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "402": {
        "ID": "402",
        "Name": "2 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "Two",
        "Planet": "Jupiter",
        "Sign": "Capricorn",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "403": {
        "ID": "403",
        "Name": "3 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "Three",
        "Planet": "Mars",
        "Sign": "Capricorn",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "404": {
        "ID": "404",
        "Name": "4 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "Four",
        "Planet": "Sun",
        "Sign": "Capricorn",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "405": {
        "ID": "405",
        "Name": "5 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "Five",
        "Planet": "Mercury",
        "Sign": "Taurus",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "406": {
        "ID": "406",
        "Name": "6 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "Six",
        "Planet": "Moon",
        "Sign": "Taurus",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "407": {
        "ID": "407",
        "Name": "7 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "Seven",
        "Planet": "Saturn",
        "Sign": "Taurus",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "408": {
        "ID": "408",
        "Name": "8 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "Eight",
        "Planet": "Sun",
        "Sign": "Virgo",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "409": {
        "ID": "409",
        "Name": "9 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "Nine",
        "Planet": "Venus",
        "Sign": "Virgo",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "410": {
        "ID": "410",
        "Name": "10 of Pentacles",
        "Suit": "Pentacles",
        "Type": "Minors",
        "Numerology": "One",
        "Planet": "Mercury",
        "Sign": "Virgo",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "411": {
        "ID": "411",
        "Name": "Page of Pentacles",
        "Suit": "Pentacles",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "412": {
        "ID": "412",
        "Name": "Knight of Pentacles",
        "Suit": "Pentacles",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "413": {
        "ID": "413",
        "Name": "Queen of Pentacles",
        "Suit": "Pentacles",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "414": {
        "ID": "414",
        "Name": "King of Pentacles",
        "Suit": "Pentacles",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Earth",
        "Septenary": "",
        "Vertical": ""
    },
    "301": {
        "ID": "301",
        "Name": "Ace of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "One",
        "Planet": "",
        "Sign": "",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "302": {
        "ID": "302",
        "Name": "2 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "Two",
        "Planet": "Moon",
        "Sign": "Libra",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "303": {
        "ID": "303",
        "Name": "3 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "Three",
        "Planet": "Saturn",
        "Sign": "Libra",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "304": {
        "ID": "304",
        "Name": "4 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "Four",
        "Planet": "Jupiter",
        "Sign": "Libra",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "305": {
        "ID": "305",
        "Name": "5 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "Five",
        "Planet": "Venus",
        "Sign": "Aquarius",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "306": {
        "ID": "306",
        "Name": "6 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "Six",
        "Planet": "Mercury",
        "Sign": "Aquarius",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "307": {
        "ID": "307",
        "Name": "7 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "Seven",
        "Planet": "Moon",
        "Sign": "Aquarius",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "308": {
        "ID": "308",
        "Name": "8 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "Eight",
        "Planet": "Jupiter",
        "Sign": "Gemini",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "309": {
        "ID": "309",
        "Name": "9 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "Nine",
        "Planet": "Mars",
        "Sign": "Gemini",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "310": {
        "ID": "310",
        "Name": "10 of Swords",
        "Suit": "Swords",
        "Type": "Minors",
        "Numerology": "One",
        "Planet": "Sun",
        "Sign": "Gemini",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "311": {
        "ID": "311",
        "Name": "Page of Swords",
        "Suit": "Swords",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "312": {
        "ID": "312",
        "Name": "Knight of Swords",
        "Suit": "Swords",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "313": {
        "ID": "313",
        "Name": "Queen of Swords",
        "Suit": "Swords",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    },
    "314": {
        "ID": "314",
        "Name": "King of Swords",
        "Suit": "Swords",
        "Type": "Court",
        "Numerology": "",
        "Planet": "",
        "Sign": "",
        "Element": "Air",
        "Septenary": "",
        "Vertical": ""
    }
}

// Gobernantes tradicionales
const traditionalRulers = {
    // Signs and their rulers (planet, major card)
    'Aries': ['Mars', 'The Emperor'],
    'Taurus': ['Venus', 'The Hierophant'],
    'Gemini': ['Mercury', 'The Lovers'],
    'Cancer': ['Moon', 'The Chariot'],
    'Leo': ['Sun', 'Strength'],
    'Virgo': ['Mercury', 'The Hermit'],
    'Libra': ['Venus', 'Justice'],
    'Scorpio': ['Mars', 'Death'],
    'Sagittarius': ['Jupiter', 'Temperance'],
    'Capricorn': ['Saturn', 'The Devil'],
    'Aquarius': ['Saturn', 'The Star'],
    'Pisces': ['Jupiter', 'The Moon'],
    
    // Planets and their major cards
    'Sun': ['The Sun', null],
    'Moon': ['The High Priestess', null],
    'Mercury': ['The Magician', null],
    'Venus': ['The Empress', null],
    'Mars': ['The Tower', null],
    'Jupiter': ['Wheel Of Fortune', null],
    'Saturn': ['The World', null],
    'Uranus': ['The Fool', null],
    'Neptune': ['The Hanged Man', null],
    'Pluto': ['Judgment', null]
};

// Configuraciones y constantes
const monthOrder = {
    "January": 1, "February": 2, "March": 3, "April": 4, "May": 5, "June": 6,
    "July": 7, "August": 8, "September": 9, "October": 10, "November": 11, "December": 12
};

const categoryOrders = {
    "element": ["Fire", "Water", "Air", "Earth"],
    "planet": ["Saturn", "Jupiter", "Mars", "Sun", "Venus", "Mercury", "Moon"],
    "sign": ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
            "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"],
    "type": ["Majors", "Minors", "Court"],
    "septenary": ["Zero", "First", "Second", "Third"],
    "vertical": ["Zero", "First", "Second", "Third", "Fourth", "Fifth", "Sixth", "Seventh"]
};

const chartColors = [
    "#334D5C", "#5D8A66", "#B38D72", "#7A6A95", "#4B8F8C",
    "#9E5A63", "#6B5B7B", "#456D7A", "#A37C45", "#7A9E9F",
    "#8C6B5D", "#5D737E"
];


